language: node_js
node_js:
- '9'
install:
- npm i -g gulp
script:
- gulp
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local-dir: dist
